### ISSUE TITLE
https vs http

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflo.ws#6]
Moving this from agent / #23.

From @almereyda: 
Can I assist in setting up TLS for https://valueflo.ws, which doesn't work
yet?
It seems we should make it available right from the start, so no http links
get spawned over the web.

From Lynn:
@almereyda sounds like a good idea. Does the certificate cost much?

**Comment by ahdinosaur** [comment]
super keen on using https-only asap, i'll take care of this.
- i'll setup a dokku server to host our site, since GitHub pages over a custom domain doesn't support HTTPS 
- i'll buy a certificate, any recommendations?

(note to myself: it'd be sweet to continue using this public repo for our website deploys, then maybe automated deploys from here to dokku?)

**Comment by elf-pavlik** [comment]
@ahdinosaur I guess @almereyda suggested using http://www.startssl.com/
he also has dokku host running on http://co-munity.net/ecobytes which I believe we could deploy to
Since we need a build process we should ASAP configure github webhooks and start hosting the site ourselves. To support content negotiation for the vocab (JSON-LD, Turtle, RDFa) we may end up needing a small daemon, I happily will put one together using http://hapijs.com/

**Comment by ahdinosaur** [comment]
> @elf-pavlik: To support content negotiation for the vocab (JSON-LD, Turtle, RDFa) we may end up needing a small daemon

can you unpack this a bit, to make sure i understand?

i am imagining we need to support [HTTP `Accepts` header](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.1), so as an example the following request:

```
GET /ns/Agent HTTP/1.1
Host: valueflo.ws
Accept: text/turtle

```

should return the contents of http://valueflo.ws/ns/Agent.ttl. is that right? if so then this should be trivial with a couple tiny npm modules ([accepts](https://www.npmjs.com/package/accepts) and [serve-static](https://www.npmjs.com/package/serve-static)), might be useful to other folks.

i could also see us supporting [`Accept-Language`](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.4), but that adds quite a bit of complexity as it relies on parsing and reformatting the rdf triples so maybe much much later.

**Comment by ahdinosaur** [comment]
done: https://valueflo.ws, closing.
